name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull from hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "roby.ramos.spfc@gmail.com"
          git config user.name "robyramos86"
          git pull https://robyramos:$HF_TOKEN@huggingface.co/spaces/robyramos/smart main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://robyramos:$HF_TOKEN@huggingface.co/spaces/robyramos/smart main
